// Generates supabase/migrations/001_init.sql from the app's own data (district ids, collection sizes),
// so the database constraints can never drift from the client. Run: npm run gen:sql
import fs from 'node:fs'
import { COLLECTIONS } from '../src/collections/index.ts'
import { DISTRICTS } from '../src/data/districts.ts'

const q = (s: string) => `'${s.replace(/'/g, "''")}'`

const sql = `-- আমি খেয়েছি — district leaderboard schema.
-- Generated by scripts/gen-sql.ts. Re-run that script (not hand edits) when collections change.
-- Prerequisites in the Supabase dashboard:
--   Authentication → Sign In / Providers → enable "Allow anonymous sign-ins"
--   (recommended) Authentication → Attack Protection → enable CAPTCHA with Cloudflare Turnstile

-- ---------- reference data ----------
create table if not exists public.districts (
  id text primary key,
  name_bn text not null,
  division text not null
);

insert into public.districts (id, name_bn, division) values
${DISTRICTS.map((d) => `  (${q(d.id)}, ${q(d.bn)}, ${q(d.division)})`).join(',\n')}
on conflict (id) do update set name_bn = excluded.name_bn, division = excluded.division;

create table if not exists public.collections (
  id text primary key,
  max_count int not null,
  max_score int not null
);

insert into public.collections (id, max_count, max_score) values
${COLLECTIONS.map((c) => `  (${q(c.id)}, ${c.items.length}, ${c.items.length * 3})`).join(',\n')}
on conflict (id) do update set max_count = excluded.max_count, max_score = excluded.max_score;

alter table public.districts enable row level security;
alter table public.collections enable row level security;
drop policy if exists "districts readable" on public.districts;
create policy "districts readable" on public.districts for select to anon, authenticated using (true);
drop policy if exists "collections readable" on public.collections;
create policy "collections readable" on public.collections for select to anon, authenticated using (true);

-- ---------- scores: one row per (anonymous) user per collection ----------
create table if not exists public.scores (
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  collection text not null references public.collections (id),
  home_district text not null references public.districts (id),
  score int not null check (score >= 0),
  count int not null check (count >= 0 and score >= count),
  levels text not null check (levels ~ '^[A-Za-z0-9_-]{1,200}$'),
  updated_at timestamptz not null default now(),
  primary key (user_id, collection)
);

create index if not exists scores_collection_district on public.scores (collection, home_district);

-- Range-check against the collection size and stamp updated_at.
create or replace function public.scores_validate() returns trigger
language plpgsql set search_path = public as $$
declare lim public.collections%rowtype;
begin
  select * into lim from public.collections where id = new.collection;
  if not found then raise exception 'unknown collection %', new.collection; end if;
  if new.count > lim.max_count or new.score > lim.max_score or new.score > new.count * 3 then
    raise exception 'score out of range';
  end if;
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists scores_validate on public.scores;
create trigger scores_validate before insert or update on public.scores
  for each row execute function public.scores_validate();

alter table public.scores enable row level security;

-- Users can only see and write their own row; nobody can list other people's rows.
drop policy if exists "own row select" on public.scores;
create policy "own row select" on public.scores for select to authenticated using (user_id = auth.uid());
drop policy if exists "own row insert" on public.scores;
create policy "own row insert" on public.scores for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "own row update" on public.scores;
create policy "own row update" on public.scores for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

revoke all on public.scores from anon;
grant select, insert, update on public.scores to authenticated;

-- ---------- public aggregates ----------
-- Ranked by a Bayesian average so a district with 5 players can't top one with 5,000 by luck:
--   rank_score = (sum + C * global_mean) / (n + C), with C = 20.
-- Only districts with at least 5 players are listed.
create or replace function public.leaderboard(p_collection text)
returns table (district_id text, participants bigint, avg_score numeric, avg_count numeric, rank_score numeric)
language sql stable security definer set search_path = public as $$
  with g as (
    select coalesce(avg(score), 0)::numeric as mean from public.scores where collection = p_collection
  ), d as (
    select home_district, count(*) as n, sum(score)::numeric as s, avg(score)::numeric as a, avg(count)::numeric as ac
    from public.scores where collection = p_collection
    group by home_district
  )
  select d.home_district, d.n, round(d.a, 2), round(d.ac, 2),
         round((d.s + 20 * g.mean) / (d.n + 20), 3)
  from d, g
  where d.n >= 5
  order by 5 desc, d.n desc;
$$;

create or replace function public.leaderboard_total(p_collection text)
returns bigint
language sql stable security definer set search_path = public as $$
  select count(*) from public.scores where collection = p_collection;
$$;

revoke all on function public.leaderboard(text) from public;
revoke all on function public.leaderboard_total(text) from public;
grant execute on function public.leaderboard(text) to anon, authenticated;
grant execute on function public.leaderboard_total(text) to anon, authenticated;
`

fs.mkdirSync('supabase/migrations', { recursive: true })
fs.writeFileSync('supabase/migrations/001_init.sql', sql)
console.log(`wrote supabase/migrations/001_init.sql (${DISTRICTS.length} districts, ${COLLECTIONS.length} collections)`)
