// Writes docs/DATA-REVIEW.md: every district food marked `uncertain`, with its sources, for a human pass
// before launch. Run: npm run review
import fs from 'node:fs'
import { DISTRICT_BY_ID } from '../src/data/districts.ts'

type Food = { bn: string; uncertain: boolean; sources: string[] }
const data = JSON.parse(fs.readFileSync('src/data/food64.json', 'utf8')) as Record<string, Food[]>

const rows: string[] = []
let signature = 0
for (const [id, foods] of Object.entries(data)) {
  foods.forEach((f, i) => {
    if (!f.uncertain) return
    if (i === 0) signature++
    const src = f.sources.length ? f.sources.map((s, j) => `[${j + 1}](${s})`).join(' ') : '—'
    rows.push(`| ${DISTRICT_BY_ID[id].bn} (${id}) | ${f.bn}${i === 0 ? ' **(সিগনেচার)**' : ''} | ${src} |`)
  })
}

const shared = new Map<string, string[]>()
for (const [id, foods] of Object.entries(data)) {
  const k = foods[0].bn
  shared.set(k, [...(shared.get(k) ?? []), DISTRICT_BY_ID[id].bn])
}
const dupes = [...shared].filter(([, v]) => v.length > 1).map(([k, v]) => `- **${k}**: ${v.join(', ')}`)

const md = `# ডেটা রিভিউ চেকলিস্ট

Generated by \`npm run review\` from \`src/data/food64.json\`. Items marked uncertain were weakly sourced, often only
by the widely copied "৬৪ জেলার বিখ্যাত খাবার" lists. To fix one, edit \`research/districts-*.json\`, then run
\`npm run import:data && npm run review\`. Within a district, verified items are listed first, and the first item
is the "signature" shown on maps and cards.

**${rows.length} uncertain items, ${signature} of them the signature item of their district.**

| জেলা | খাবার | সূত্র |
|---|---|---|
${rows.join('\n')}

## একই সিগনেচার খাবার একাধিক জেলায়

People in the comments may argue about these. Decide whether each should stay as it is.

${dupes.join('\n')}

## পিঠা ও দেশি ফল: research notes to check

- **পিঠা:**
  - নকশি, পাকন and মুগ পাকন are kept as three separate items. Bangla Wikipedia treats পাকন as another name for নকশি.
  - "সেমাই পিঠা" is used for the Bagerhat dish (pressed noodles eaten with meat curry). The sweet version in milk is listed as চুষি.
  - These have weak sources: পাতা পিঠা, খুদের পিঠা, বড়া পিঠা, ছেছমা পিঠা and ঝাল পোয়া.
- **দেশি ফল:**
  - Contested scientific names: আমড়া (*Spondias dulcis* vs *S. pinnata*), লটকন (*Baccaurea ramiflora*) and লেবু (*C. aurantiifolia*).
  - আতা/শরিফা are merged into one item.
  - ডুমুর and সাতকরা are mostly cooked, so they're borderline as fruits.
  - The seasons for ডালিম, গাব and ডেফল are thinly sourced.
`

fs.writeFileSync('docs/DATA-REVIEW.md', md)
console.log(`docs/DATA-REVIEW.md: ${rows.length} uncertain, ${signature} signature`)
